### Video output (Hyprland-safe)
vo=gpu
gpu-context=wayland
icc-profile-auto=no
target-colorspace-hint=no

### Scaling
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

### Color & dithering
video-output-levels=auto
dither-depth=auto
dither=fruit

### Timing
video-sync=audio
interpolation=no

### Subtitles
sub-ass-use-video-data=all
sub-ass-override=no
sub-scale=1

### Audio
ao=pipewire
audio-channels=auto
# audio-resample-filter-size=16
# audio-resample-phase-shift=10

### Usability
save-position-on-quit=yes
keep-open=yes
autofit-larger=95%x95%

### Cache
cache=yes
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=128MiB

### Debug
msg-level=vo=v
