# -*- conf -*-

[main]
font=IosevkaTermSlab Nerd Font Mono:size=13
font-bold=IosevkaTermSlab Nerd Font Mono:style=Bold:size=13
font-italic=IosevkaTermSlab Nerd Font Mono:style=Italic:size=13
font-bold-italic=IosevkaTermSlab Nerd Font Mono:style=Bold Italic:size=13
pad=8x8
dpi-aware=yes

[bell]
urgent=no
notify=no
visual=no

[scrollback]
lines=10000

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

# Lain palette; see lain-colors.md
[colors-dark]
alpha=0.9
background=000000
foreground=CE7688

selection-foreground=000000
selection-background=C1B48E

# regular (0-7)
regular0=1A1A1A
regular1=A05969
regular2=897F63
regular3=C1B48E
regular4=804654
regular5=CE7688
regular6=A49978
regular7=BABABA

# bright (8-15)
bright0=4A4A4A
bright1=CE7688
bright2=A49978
bright3=C1B48E
bright4=965363
bright5=FFB1C3
bright6=B5A985
bright7=FFFFFF

urls=C1B48E

# vim: ft=dosini
